// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbsqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO auth.users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, is_active, created_at, updated_at
`

type CreateUserParams struct {
	Username     string
	Email        string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (AuthUser, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, username, email, password_hash, is_active, created_at, updated_at
FROM auth.users WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (AuthUser, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i AuthUser
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, is_active, created_at, updated_at
FROM auth.users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]AuthUser, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuthUser{}
	for rows.Next() {
		var i AuthUser
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userPermissions = `-- name: UserPermissions :many
SELECT DISTINCT p.code
FROM auth.permissions p
JOIN auth.role_permissions rp ON rp.permission_id = p.id
JOIN auth.user_roles ur ON ur.role_id = rp.role_id
WHERE ur.user_id = $1
`

func (q *Queries) UserPermissions(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, userPermissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const writeAuditLog = `-- name: WriteAuditLog :exec
INSERT INTO auth.audit_log (user_id, action, detail)
VALUES ($1, $2, $3::jsonb)
`

type WriteAuditLogParams struct {
	UserID pgtype.UUID
	Action string
	Detail []byte
}

func (q *Queries) WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) error {
	_, err := q.db.Exec(ctx, writeAuditLog, arg.UserID, arg.Action, arg.Detail)
	return err
}
