// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbsqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthAuditLog struct {
	ID        uuid.UUID
	UserID    pgtype.UUID
	Action    string
	Detail    []byte
	CreatedAt time.Time
}

type AuthPermission struct {
	ID          uuid.UUID
	Code        string
	Description pgtype.Text
}

type AuthRole struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
}

type AuthRolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
}

type AuthUser struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	IsActive     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type AuthUserBranch struct {
	UserID   uuid.UUID
	BranchID uuid.UUID
}

type AuthUserRole struct {
	UserID uuid.UUID
	RoleID uuid.UUID
}
